# Generated by Django 4.1.2 on 2022-12-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_blogs_blogss'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogss',
            new_name='Blog',
        ),
    ]
