# Generated by Django 4.1.2 on 2022-12-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_blogss_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phonenumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='internship',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
