# Generated by Django 4.1.2 on 2022-12-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_phonenumber_contact_phone_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Internship',
        ),
    ]
